// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Gallery: typeof import('./src/components/Gallery.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    SimpSearchBar: typeof import('./src/components/SimpSearchBar.vue')['default']
    SingleCard: typeof import('./src/components/SingleCard.vue')['default']
  }
}
